# Appearance

appearance:
  theme_day: minimal
  theme_night: 
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Casa del Popolo di Settignano'
    description: 'Dal 1946 promuoviamo territorio, cultura, politica, arte, socialità, musica, cineforum, centri estivi, ludoteca, attività ricreative, formazione.'
    twitter: ''
  analytics:
    google_analytics: 'G-QYC10ZJXYY'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

footer:
  copyright:
    notice: ''
    license:
      enable: false
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2 Jan 2006'
  time_format: '15:04'
  address_format: fr-fr
# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/settignano/cdp.settignano.org'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
